spring:
  profiles:
    active: dev
  datasource:
    mysql:
      url: jdbc:mysql://192.168.0.106:3306/aiops?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false
      username: root
      password:: 123456
      driver-class-name: com.mysql.jdbc.Driver
    postgres:
      url: jdbc:postgresql://192.168.0.106:5432/aiops?useUnicode==true&amp;charactorEncoding=UTF-8&amp;autoReconnect=true
      username: postgres
      password: 123456
      driver-class-name: org.postgresql.Driver
server:
  port: 9000